### ISSUE TITLE
Get project ID from node metadata

### ISSUE THREAD

**Issue by bondjimbond** [MorganDawe/tk_labels#7] opened 2022-08-05 13:26 UTC
The LocalContexts API provides the notice types based on the Project ID you send it. So rather than a field with a notice type to generate the badge, this module should instead retrieve the Project ID from the object metadata (and not block configuration), send it to the LC API, and return the notice that LocalContexts provides.

**Comment by willtp87** [comment] 2022-08-05 13:34
This would let the module support more than one project.

**Comment by bondjimbond** [comment] 2022-08-05 13:41
The way the API works, the only thing you need to provide is the Project ID. You just need to program the block to nicely display whatever data is returned from the API request. See the [how it works section on the I7 module instructions](https://docs.google.com/document/d/1QHZuCZwPbLvufSr1v4xoRwkaFWxZnp3TluCqwnSNLdU/edit) for a bit more info.

**Comment by willtp87** [comment] 2022-08-05 14:20
Note that the API provides every notice in the project but those may not all be applied to every object.

**Comment by bondjimbond** [comment] 2022-08-05 14:24
A Project can be a single object or an entire collection. Notices are always applied at the Project level, so if you have objects with different notices LC advise you make them different Projects.

**Comment by willtp87** [comment] 2022-08-05 14:57
After double checking with @bondjimbond it seems that supporting large collections with many disparate badge configurations therein is not necessarily a target for this API. Each sub set of TK rules is intended to be its own project managed in TK rules. This may be a more difficult workflow than required from a consumer standpoint but is as intended and may increase community agency.

**Comment by bondjimbond** [comment] 2022-08-05 16:13
[Some documentation about working in the Local Contexts Hub](https://docs.google.com/document/d/1x0RsD2Wp405Se3II5UzYXZj9Si-z7mCR3AM9Xy1Oeug/edit)

**Comment by MorganDawe** [comment] 2022-08-05 17:15
Thank you @bondjimbond for your support. Looks like @willtp87 has been able to resolve this issue, i am moving to close.

**Closed as completed by MorganDawe** 2022-08-05 17:15 UTC
